name: Static checkers

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  static-checkers:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        # Need history on all branches for manifest-checker to work
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      env:
        TOXENV: "manifest-checker,newsfragment"
      run: |
        python -m pip install --upgrade pip tox
        tox --notest

    - name: Check newsfragment
      env:
        TOXENV: "newsfragment"
      run: |
        tox -q

    - name: Check manifest-checker
      env:
        TOXENV: "manifest-checker"
      run: |
        tox -q
